CREATE TABLE IF NOT EXISTS users (
	id         VARCHAR(20)  NOT NULL PRIMARY KEY,
	password   VARCHAR(60)  NOT NULL, -- bcrypt hash
	name       VARCHAR(20)  NOT NULL,
	email      VARCHAR(100) NOT NULL,
	created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
